// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/scheduler/scheduler.proto

package schedulerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_QUEUED      JobState = 2
	JobState_JOB_STATE_RUNNING     JobState = 3
	JobState_JOB_STATE_COMPLETED   JobState = 4
	JobState_JOB_STATE_FAILED      JobState = 5
	JobState_JOB_STATE_CANCELLED   JobState = 6
	JobState_JOB_STATE_RETRYING    JobState = 7
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_QUEUED",
		3: "JOB_STATE_RUNNING",
		4: "JOB_STATE_COMPLETED",
		5: "JOB_STATE_FAILED",
		6: "JOB_STATE_CANCELLED",
		7: "JOB_STATE_RETRYING",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_QUEUED":      2,
		"JOB_STATE_RUNNING":     3,
		"JOB_STATE_COMPLETED":   4,
		"JOB_STATE_FAILED":      5,
		"JOB_STATE_CANCELLED":   6,
		"JOB_STATE_RETRYING":    7,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_scheduler_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_proto_scheduler_scheduler_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_QUEUED      TaskState = 2
	TaskState_TASK_STATE_RUNNING     TaskState = 3
	TaskState_TASK_STATE_COMPLETED   TaskState = 4
	TaskState_TASK_STATE_FAILED      TaskState = 5
	TaskState_TASK_STATE_CANCELLED   TaskState = 6
	TaskState_TASK_STATE_RETRYING    TaskState = 7
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_QUEUED",
		3: "TASK_STATE_RUNNING",
		4: "TASK_STATE_COMPLETED",
		5: "TASK_STATE_FAILED",
		6: "TASK_STATE_CANCELLED",
		7: "TASK_STATE_RETRYING",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_QUEUED":      2,
		"TASK_STATE_RUNNING":     3,
		"TASK_STATE_COMPLETED":   4,
		"TASK_STATE_FAILED":      5,
		"TASK_STATE_CANCELLED":   6,
		"TASK_STATE_RETRYING":    7,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_scheduler_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_proto_scheduler_scheduler_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

type WorkerState int32

const (
	WorkerState_WORKER_STATE_UNSPECIFIED WorkerState = 0
	WorkerState_WORKER_STATE_ACTIVE      WorkerState = 1
	WorkerState_WORKER_STATE_DRAINING    WorkerState = 2
	WorkerState_WORKER_STATE_DEAD        WorkerState = 3
)

// Enum value maps for WorkerState.
var (
	WorkerState_name = map[int32]string{
		0: "WORKER_STATE_UNSPECIFIED",
		1: "WORKER_STATE_ACTIVE",
		2: "WORKER_STATE_DRAINING",
		3: "WORKER_STATE_DEAD",
	}
	WorkerState_value = map[string]int32{
		"WORKER_STATE_UNSPECIFIED": 0,
		"WORKER_STATE_ACTIVE":      1,
		"WORKER_STATE_DRAINING":    2,
		"WORKER_STATE_DEAD":        3,
	}
)

func (x WorkerState) Enum() *WorkerState {
	p := new(WorkerState)
	*p = x
	return p
}

func (x WorkerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_scheduler_proto_enumTypes[2].Descriptor()
}

func (WorkerState) Type() protoreflect.EnumType {
	return &file_proto_scheduler_scheduler_proto_enumTypes[2]
}

func (x WorkerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerState.Descriptor instead.
func (WorkerState) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Gpus          int32                  `protobuf:"varint,3,opt,name=gpus,proto3" json:"gpus,omitempty"`
	DiskMb        int64                  `protobuf:"varint,4,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRequirements) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceRequirements) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceRequirements) GetGpus() int32 {
	if x != nil {
		return x.Gpus
	}
	return 0
}

func (x *ResourceRequirements) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

type ResourceCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *ResourceRequirements  `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Available     *ResourceRequirements  `protobuf:"bytes,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceCapacity) Reset() {
	*x = ResourceCapacity{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCapacity) ProtoMessage() {}

func (x *ResourceCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCapacity.ProtoReflect.Descriptor instead.
func (*ResourceCapacity) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceCapacity) GetTotal() *ResourceRequirements {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *ResourceCapacity) GetAvailable() *ResourceRequirements {
	if x != nil {
		return x.Available
	}
	return nil
}

type RetryPolicy struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries        int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	InitialBackoffMs  int64                  `protobuf:"varint,2,opt,name=initial_backoff_ms,json=initialBackoffMs,proto3" json:"initial_backoff_ms,omitempty"`
	MaxBackoffMs      int64                  `protobuf:"varint,3,opt,name=max_backoff_ms,json=maxBackoffMs,proto3" json:"max_backoff_ms,omitempty"`
	BackoffMultiplier float64                `protobuf:"fixed64,4,opt,name=backoff_multiplier,json=backoffMultiplier,proto3" json:"backoff_multiplier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RetryPolicy) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RetryPolicy) GetInitialBackoffMs() int64 {
	if x != nil {
		return x.InitialBackoffMs
	}
	return 0
}

func (x *RetryPolicy) GetMaxBackoffMs() int64 {
	if x != nil {
		return x.MaxBackoffMs
	}
	return 0
}

func (x *RetryPolicy) GetBackoffMultiplier() float64 {
	if x != nil {
		return x.BackoffMultiplier
	}
	return 0
}

type Task struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId                string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Command              string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args                 []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	State                TaskState              `protobuf:"varint,6,opt,name=state,proto3,enum=scheduler.TaskState" json:"state,omitempty"`
	AssignedWorker       string                 `protobuf:"bytes,7,opt,name=assigned_worker,json=assignedWorker,proto3" json:"assigned_worker,omitempty"`
	Attempt              int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxRetries           int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	ResourceRequirements *ResourceRequirements  `protobuf:"bytes,10,opt,name=resource_requirements,json=resourceRequirements,proto3" json:"resource_requirements,omitempty"`
	Dependencies         []string               `protobuf:"bytes,11,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Stdout               string                 `protobuf:"bytes,14,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string                 `protobuf:"bytes,15,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode             int32                  `protobuf:"varint,16,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,17,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetAssignedWorker() string {
	if x != nil {
		return x.AssignedWorker
	}
	return ""
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Task) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Task) GetResourceRequirements() *ResourceRequirements {
	if x != nil {
		return x.ResourceRequirements
	}
	return nil
}

func (x *Task) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *Task) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *Task) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Task) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	State         JobState               `protobuf:"varint,5,opt,name=state,proto3,enum=scheduler.JobState" json:"state,omitempty"`
	RetryPolicy   *RetryPolicy           `protobuf:"bytes,6,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Job) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *Job) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Job) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DAGEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromTask      string                 `protobuf:"bytes,1,opt,name=from_task,json=fromTask,proto3" json:"from_task,omitempty"`
	ToTask        string                 `protobuf:"bytes,2,opt,name=to_task,json=toTask,proto3" json:"to_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAGEdge) Reset() {
	*x = DAGEdge{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGEdge) ProtoMessage() {}

func (x *DAGEdge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGEdge.ProtoReflect.Descriptor instead.
func (*DAGEdge) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *DAGEdge) GetFromTask() string {
	if x != nil {
		return x.FromTask
	}
	return ""
}

func (x *DAGEdge) GetToTask() string {
	if x != nil {
		return x.ToTask
	}
	return ""
}

type DAGDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Edges         []*DAGEdge             `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	RetryPolicy   *RetryPolicy           `protobuf:"bytes,6,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DAGDefinition) Reset() {
	*x = DAGDefinition{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DAGDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGDefinition) ProtoMessage() {}

func (x *DAGDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGDefinition.ProtoReflect.Descriptor instead.
func (*DAGDefinition) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *DAGDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DAGDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DAGDefinition) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DAGDefinition) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *DAGDefinition) GetEdges() []*DAGEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *DAGDefinition) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

type WorkerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	State          WorkerState            `protobuf:"varint,3,opt,name=state,proto3,enum=scheduler.WorkerState" json:"state,omitempty"`
	Resources      *ResourceCapacity      `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	RunningTaskIds []string               `protobuf:"bytes,5,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"`
	LastHeartbeat  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WorkerInfo) GetState() WorkerState {
	if x != nil {
		return x.State
	}
	return WorkerState_WORKER_STATE_UNSPECIFIED
}

func (x *WorkerInfo) GetResources() *ResourceCapacity {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkerInfo) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

func (x *WorkerInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	RetryPolicy   *RetryPolicy           `protobuf:"bytes,4,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *SubmitJobRequest) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type SubmitDAGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dag           *DAGDefinition         `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDAGRequest) Reset() {
	*x = SubmitDAGRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDAGRequest) ProtoMessage() {}

func (x *SubmitDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDAGRequest.ProtoReflect.Descriptor instead.
func (*SubmitDAGRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitDAGRequest) GetDag() *DAGDefinition {
	if x != nil {
		return x.Dag
	}
	return nil
}

type SubmitDAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DagId         string                 `protobuf:"bytes,1,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDAGResponse) Reset() {
	*x = SubmitDAGResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDAGResponse) ProtoMessage() {}

func (x *SubmitDAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDAGResponse.ProtoReflect.Descriptor instead.
func (*SubmitDAGResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitDAGResponse) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *SubmitDAGResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *GetJobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterState   JobState               `protobuf:"varint,1,opt,name=filter_state,json=filterState,proto3,enum=scheduler.JobState" json:"filter_state,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *ListJobsRequest) GetFilterState() JobState {
	if x != nil {
		return x.FilterState
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{18}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerInfo          `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *ListWorkersResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Resources     *ResourceCapacity      `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerRequest) GetResources() *ResourceCapacity {
	if x != nil {
		return x.Resources
	}
	return nil
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterWorkerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterWorkerResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Resources      *ResourceCapacity      `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	RunningTaskIds []string               `protobuf:"bytes,3,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetResources() *ResourceCapacity {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	CancelTaskIds []string               `protobuf:"bytes,2,rep,name=cancel_task_ids,json=cancelTaskIds,proto3" json:"cancel_task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{23}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetCancelTaskIds() []string {
	if x != nil {
		return x.CancelTaskIds
	}
	return nil
}

type ReportTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         TaskState              `protobuf:"varint,4,opt,name=state,proto3,enum=scheduler.TaskState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusRequest) Reset() {
	*x = ReportTaskStatusRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusRequest) ProtoMessage() {}

func (x *ReportTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{24}
}

func (x *ReportTaskStatusRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *ReportTaskStatusRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportTaskStatusRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ReportTaskStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStatusResponse) Reset() {
	*x = ReportTaskStatusResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStatusResponse) ProtoMessage() {}

func (x *ReportTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{25}
}

func (x *ReportTaskStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{26}
}

func (x *AssignTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type AssignTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskResponse) Reset() {
	*x = AssignTaskResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskResponse) ProtoMessage() {}

func (x *AssignTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskResponse.ProtoReflect.Descriptor instead.
func (*AssignTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{27}
}

func (x *AssignTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AssignTaskResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{28}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_scheduler_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_scheduler_proto_rawDescGZIP(), []int{29}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_scheduler_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/scheduler/scheduler.proto\x12\tscheduler\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x14ResourceRequirements\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12\x12\n" +
	"\x04gpus\x18\x03 \x01(\x05R\x04gpus\x12\x17\n" +
	"\adisk_mb\x18\x04 \x01(\x03R\x06diskMb\"\x88\x01\n" +
	"\x10ResourceCapacity\x125\n" +
	"\x05total\x18\x01 \x01(\v2\x1f.scheduler.ResourceRequirementsR\x05total\x12=\n" +
	"\tavailable\x18\x02 \x01(\v2\x1f.scheduler.ResourceRequirementsR\tavailable\"\xb1\x01\n" +
	"\vRetryPolicy\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12,\n" +
	"\x12initial_backoff_ms\x18\x02 \x01(\x03R\x10initialBackoffMs\x12$\n" +
	"\x0emax_backoff_ms\x18\x03 \x01(\x03R\fmaxBackoffMs\x12-\n" +
	"\x12backoff_multiplier\x18\x04 \x01(\x01R\x11backoffMultiplier\"\xe1\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12*\n" +
	"\x05state\x18\x06 \x01(\x0e2\x14.scheduler.TaskStateR\x05state\x12'\n" +
	"\x0fassigned_worker\x18\a \x01(\tR\x0eassignedWorker\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\x12T\n" +
	"\x15resource_requirements\x18\n" +
	" \x01(\v2\x1f.scheduler.ResourceRequirementsR\x14resourceRequirements\x12\"\n" +
	"\fdependencies\x18\v \x03(\tR\fdependencies\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06stdout\x18\x0e \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x0f \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x10 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x11 \x01(\tR\ferrorMessage\"\xed\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12%\n" +
	"\x05tasks\x18\x04 \x03(\v2\x0f.scheduler.TaskR\x05tasks\x12)\n" +
	"\x05state\x18\x05 \x01(\x0e2\x13.scheduler.JobStateR\x05state\x129\n" +
	"\fretry_policy\x18\x06 \x01(\v2\x16.scheduler.RetryPolicyR\vretryPolicy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"?\n" +
	"\aDAGEdge\x12\x1b\n" +
	"\tfrom_task\x18\x01 \x01(\tR\bfromTask\x12\x17\n" +
	"\ato_task\x18\x02 \x01(\tR\x06toTask\"\xdb\x01\n" +
	"\rDAGDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12%\n" +
	"\x05tasks\x18\x04 \x03(\v2\x0f.scheduler.TaskR\x05tasks\x12(\n" +
	"\x05edges\x18\x05 \x03(\v2\x12.scheduler.DAGEdgeR\x05edges\x129\n" +
	"\fretry_policy\x18\x06 \x01(\v2\x16.scheduler.RetryPolicyR\vretryPolicy\"\x8c\x02\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.scheduler.WorkerStateR\x05state\x129\n" +
	"\tresources\x18\x04 \x01(\v2\x1b.scheduler.ResourceCapacityR\tresources\x12(\n" +
	"\x10running_task_ids\x18\x05 \x03(\tR\x0erunningTaskIds\x12A\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"\xa4\x01\n" +
	"\x10SubmitJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12%\n" +
	"\x05tasks\x18\x03 \x03(\v2\x0f.scheduler.TaskR\x05tasks\x129\n" +
	"\fretry_policy\x18\x04 \x01(\v2\x16.scheduler.RetryPolicyR\vretryPolicy\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\">\n" +
	"\x10SubmitDAGRequest\x12*\n" +
	"\x03dag\x18\x01 \x01(\v2\x18.scheduler.DAGDefinitionR\x03dag\"A\n" +
	"\x11SubmitDAGResponse\x12\x15\n" +
	"\x06dag_id\x18\x01 \x01(\tR\x05dagId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"8\n" +
	"\x14GetJobStatusResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.scheduler.JobR\x03job\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"-\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x0fListJobsRequest\x126\n" +
	"\ffilter_state\x18\x01 \x01(\x0e2\x13.scheduler.JobStateR\vfilterState\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"6\n" +
	"\x10ListJobsResponse\x12\"\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0e.scheduler.JobR\x04jobs\"\x14\n" +
	"\x12ListWorkersRequest\"F\n" +
	"\x13ListWorkersResponse\x12/\n" +
	"\aworkers\x18\x01 \x03(\v2\x15.scheduler.WorkerInfoR\aworkers\"\x89\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x129\n" +
	"\tresources\x18\x03 \x01(\v2\x1b.scheduler.ResourceCapacityR\tresources\"[\n" +
	"\x16RegisterWorkerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\"\x94\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x129\n" +
	"\tresources\x18\x02 \x01(\v2\x1b.scheduler.ResourceCapacityR\tresources\x12(\n" +
	"\x10running_task_ids\x18\x03 \x03(\tR\x0erunningTaskIds\"_\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12&\n" +
	"\x0fcancel_task_ids\x18\x02 \x03(\tR\rcancelTaskIds\"\x84\x02\n" +
	"\x17ReportTaskStatusRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12*\n" +
	"\x05state\x18\x04 \x01(\x0e2\x14.scheduler.TaskStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\">\n" +
	"\x18ReportTaskStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"8\n" +
	"\x11AssignTaskRequest\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.scheduler.TaskR\x04task\"H\n" +
	"\x12AssignTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xc9\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x14\n" +
	"\x10JOB_STATE_QUEUED\x10\x02\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x03\x12\x17\n" +
	"\x13JOB_STATE_COMPLETED\x10\x04\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x05\x12\x17\n" +
	"\x13JOB_STATE_CANCELLED\x10\x06\x12\x16\n" +
	"\x12JOB_STATE_RETRYING\x10\a*\xd2\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11TASK_STATE_QUEUED\x10\x02\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x03\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x04\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x05\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\x06\x12\x17\n" +
	"\x13TASK_STATE_RETRYING\x10\a*v\n" +
	"\vWorkerState\x12\x1c\n" +
	"\x18WORKER_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13WORKER_STATE_ACTIVE\x10\x01\x12\x19\n" +
	"\x15WORKER_STATE_DRAINING\x10\x02\x12\x15\n" +
	"\x11WORKER_STATE_DEAD\x10\x032\xce\x03\n" +
	"\x10SchedulerService\x12F\n" +
	"\tSubmitJob\x12\x1b.scheduler.SubmitJobRequest\x1a\x1c.scheduler.SubmitJobResponse\x12F\n" +
	"\tSubmitDAG\x12\x1b.scheduler.SubmitDAGRequest\x1a\x1c.scheduler.SubmitDAGResponse\x12O\n" +
	"\fGetJobStatus\x12\x1e.scheduler.GetJobStatusRequest\x1a\x1f.scheduler.GetJobStatusResponse\x12F\n" +
	"\tCancelJob\x12\x1b.scheduler.CancelJobRequest\x1a\x1c.scheduler.CancelJobResponse\x12C\n" +
	"\bListJobs\x12\x1a.scheduler.ListJobsRequest\x1a\x1b.scheduler.ListJobsResponse\x12L\n" +
	"\vListWorkers\x12\x1d.scheduler.ListWorkersRequest\x1a\x1e.scheduler.ListWorkersResponse2\x91\x02\n" +
	"\x13CoordinationService\x12U\n" +
	"\x0eRegisterWorker\x12 .scheduler.RegisterWorkerRequest\x1a!.scheduler.RegisterWorkerResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x1c.scheduler.HeartbeatResponse\x12[\n" +
	"\x10ReportTaskStatus\x12\".scheduler.ReportTaskStatusRequest\x1a#.scheduler.ReportTaskStatusResponse2\xa5\x01\n" +
	"\rWorkerService\x12I\n" +
	"\n" +
	"AssignTask\x12\x1c.scheduler.AssignTaskRequest\x1a\x1d.scheduler.AssignTaskResponse\x12I\n" +
	"\n" +
	"CancelTask\x12\x1c.scheduler.CancelTaskRequest\x1a\x1d.scheduler.CancelTaskResponseB7Z5github.com/NimayPant/job-scheduler/pkg/pb;schedulerpbb\x06proto3"

var (
	file_proto_scheduler_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_scheduler_proto_rawDesc), len(file_proto_scheduler_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_scheduler_proto_rawDescData
}

var file_proto_scheduler_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_scheduler_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_scheduler_scheduler_proto_goTypes = []any{
	(JobState)(0),                    // 0: scheduler.JobState
	(TaskState)(0),                   // 1: scheduler.TaskState
	(WorkerState)(0),                 // 2: scheduler.WorkerState
	(*ResourceRequirements)(nil),     // 3: scheduler.ResourceRequirements
	(*ResourceCapacity)(nil),         // 4: scheduler.ResourceCapacity
	(*RetryPolicy)(nil),              // 5: scheduler.RetryPolicy
	(*Task)(nil),                     // 6: scheduler.Task
	(*Job)(nil),                      // 7: scheduler.Job
	(*DAGEdge)(nil),                  // 8: scheduler.DAGEdge
	(*DAGDefinition)(nil),            // 9: scheduler.DAGDefinition
	(*WorkerInfo)(nil),               // 10: scheduler.WorkerInfo
	(*SubmitJobRequest)(nil),         // 11: scheduler.SubmitJobRequest
	(*SubmitJobResponse)(nil),        // 12: scheduler.SubmitJobResponse
	(*SubmitDAGRequest)(nil),         // 13: scheduler.SubmitDAGRequest
	(*SubmitDAGResponse)(nil),        // 14: scheduler.SubmitDAGResponse
	(*GetJobStatusRequest)(nil),      // 15: scheduler.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),     // 16: scheduler.GetJobStatusResponse
	(*CancelJobRequest)(nil),         // 17: scheduler.CancelJobRequest
	(*CancelJobResponse)(nil),        // 18: scheduler.CancelJobResponse
	(*ListJobsRequest)(nil),          // 19: scheduler.ListJobsRequest
	(*ListJobsResponse)(nil),         // 20: scheduler.ListJobsResponse
	(*ListWorkersRequest)(nil),       // 21: scheduler.ListWorkersRequest
	(*ListWorkersResponse)(nil),      // 22: scheduler.ListWorkersResponse
	(*RegisterWorkerRequest)(nil),    // 23: scheduler.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),   // 24: scheduler.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),         // 25: scheduler.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 26: scheduler.HeartbeatResponse
	(*ReportTaskStatusRequest)(nil),  // 27: scheduler.ReportTaskStatusRequest
	(*ReportTaskStatusResponse)(nil), // 28: scheduler.ReportTaskStatusResponse
	(*AssignTaskRequest)(nil),        // 29: scheduler.AssignTaskRequest
	(*AssignTaskResponse)(nil),       // 30: scheduler.AssignTaskResponse
	(*CancelTaskRequest)(nil),        // 31: scheduler.CancelTaskRequest
	(*CancelTaskResponse)(nil),       // 32: scheduler.CancelTaskResponse
	(*timestamppb.Timestamp)(nil),    // 33: google.protobuf.Timestamp
}
var file_proto_scheduler_scheduler_proto_depIdxs = []int32{
	3,  // 0: scheduler.ResourceCapacity.total:type_name -> scheduler.ResourceRequirements
	3,  // 1: scheduler.ResourceCapacity.available:type_name -> scheduler.ResourceRequirements
	1,  // 2: scheduler.Task.state:type_name -> scheduler.TaskState
	3,  // 3: scheduler.Task.resource_requirements:type_name -> scheduler.ResourceRequirements
	33, // 4: scheduler.Task.created_at:type_name -> google.protobuf.Timestamp
	33, // 5: scheduler.Task.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 6: scheduler.Job.tasks:type_name -> scheduler.Task
	0,  // 7: scheduler.Job.state:type_name -> scheduler.JobState
	5,  // 8: scheduler.Job.retry_policy:type_name -> scheduler.RetryPolicy
	33, // 9: scheduler.Job.created_at:type_name -> google.protobuf.Timestamp
	33, // 10: scheduler.Job.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 11: scheduler.DAGDefinition.tasks:type_name -> scheduler.Task
	8,  // 12: scheduler.DAGDefinition.edges:type_name -> scheduler.DAGEdge
	5,  // 13: scheduler.DAGDefinition.retry_policy:type_name -> scheduler.RetryPolicy
	2,  // 14: scheduler.WorkerInfo.state:type_name -> scheduler.WorkerState
	4,  // 15: scheduler.WorkerInfo.resources:type_name -> scheduler.ResourceCapacity
	33, // 16: scheduler.WorkerInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	6,  // 17: scheduler.SubmitJobRequest.tasks:type_name -> scheduler.Task
	5,  // 18: scheduler.SubmitJobRequest.retry_policy:type_name -> scheduler.RetryPolicy
	9,  // 19: scheduler.SubmitDAGRequest.dag:type_name -> scheduler.DAGDefinition
	7,  // 20: scheduler.GetJobStatusResponse.job:type_name -> scheduler.Job
	0,  // 21: scheduler.ListJobsRequest.filter_state:type_name -> scheduler.JobState
	7,  // 22: scheduler.ListJobsResponse.jobs:type_name -> scheduler.Job
	10, // 23: scheduler.ListWorkersResponse.workers:type_name -> scheduler.WorkerInfo
	4,  // 24: scheduler.RegisterWorkerRequest.resources:type_name -> scheduler.ResourceCapacity
	4,  // 25: scheduler.HeartbeatRequest.resources:type_name -> scheduler.ResourceCapacity
	1,  // 26: scheduler.ReportTaskStatusRequest.state:type_name -> scheduler.TaskState
	6,  // 27: scheduler.AssignTaskRequest.task:type_name -> scheduler.Task
	11, // 28: scheduler.SchedulerService.SubmitJob:input_type -> scheduler.SubmitJobRequest
	13, // 29: scheduler.SchedulerService.SubmitDAG:input_type -> scheduler.SubmitDAGRequest
	15, // 30: scheduler.SchedulerService.GetJobStatus:input_type -> scheduler.GetJobStatusRequest
	17, // 31: scheduler.SchedulerService.CancelJob:input_type -> scheduler.CancelJobRequest
	19, // 32: scheduler.SchedulerService.ListJobs:input_type -> scheduler.ListJobsRequest
	21, // 33: scheduler.SchedulerService.ListWorkers:input_type -> scheduler.ListWorkersRequest
	23, // 34: scheduler.CoordinationService.RegisterWorker:input_type -> scheduler.RegisterWorkerRequest
	25, // 35: scheduler.CoordinationService.Heartbeat:input_type -> scheduler.HeartbeatRequest
	27, // 36: scheduler.CoordinationService.ReportTaskStatus:input_type -> scheduler.ReportTaskStatusRequest
	29, // 37: scheduler.WorkerService.AssignTask:input_type -> scheduler.AssignTaskRequest
	31, // 38: scheduler.WorkerService.CancelTask:input_type -> scheduler.CancelTaskRequest
	12, // 39: scheduler.SchedulerService.SubmitJob:output_type -> scheduler.SubmitJobResponse
	14, // 40: scheduler.SchedulerService.SubmitDAG:output_type -> scheduler.SubmitDAGResponse
	16, // 41: scheduler.SchedulerService.GetJobStatus:output_type -> scheduler.GetJobStatusResponse
	18, // 42: scheduler.SchedulerService.CancelJob:output_type -> scheduler.CancelJobResponse
	20, // 43: scheduler.SchedulerService.ListJobs:output_type -> scheduler.ListJobsResponse
	22, // 44: scheduler.SchedulerService.ListWorkers:output_type -> scheduler.ListWorkersResponse
	24, // 45: scheduler.CoordinationService.RegisterWorker:output_type -> scheduler.RegisterWorkerResponse
	26, // 46: scheduler.CoordinationService.Heartbeat:output_type -> scheduler.HeartbeatResponse
	28, // 47: scheduler.CoordinationService.ReportTaskStatus:output_type -> scheduler.ReportTaskStatusResponse
	30, // 48: scheduler.WorkerService.AssignTask:output_type -> scheduler.AssignTaskResponse
	32, // 49: scheduler.WorkerService.CancelTask:output_type -> scheduler.CancelTaskResponse
	39, // [39:50] is the sub-list for method output_type
	28, // [28:39] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_scheduler_scheduler_proto_init() }
func file_proto_scheduler_scheduler_proto_init() {
	if File_proto_scheduler_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_scheduler_proto_rawDesc), len(file_proto_scheduler_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_scheduler_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_scheduler_proto_depIdxs,
		EnumInfos:         file_proto_scheduler_scheduler_proto_enumTypes,
		MessageInfos:      file_proto_scheduler_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_scheduler_proto = out.File
	file_proto_scheduler_scheduler_proto_goTypes = nil
	file_proto_scheduler_scheduler_proto_depIdxs = nil
}
